---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: order-app
  namespace: dfrey
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demo-parent
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
      - name: BP_MAVEN_BUILT_MODULE
        value: app-parent/order-app
      - name: BP_MAVEN_BUILD_ARGUMENTS
        value: package -Dmaven.test.skip=true -pl :order-app
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: kubernetes
  serviceClaims:
    - name: order-app-db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: order-app-db
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dmfrey/demo-parent.git
      ref:
        branch: develop
status:
  supplyChainRef: {}