kind: ConfigMap
apiVersion: v1
metadata:
  name: order-app
data:
  application.yml: |-
    logging.level:
      org.springframework.data: INFO
      org.springframework.web: INFO
      com.vmware.tanzulabs.app: DEBUG

    spring:

      datasource:
        url: jdbc:postgresql://order-app-db:5432/postgres

      zipkin:
        enabled: false
    
    ---
    spring:
      
      config:
        activate:
          on-profile: vault

        import: vault://

      cloud:
    
        vault:
          enabled: true
          fail-fast: true
    
          config:
            lifecycle:
              enabled: true
              min-renewal: 10m
              expiry-threshold: 10m
    
          kv.enabled: false
    
          uri: http://vault.vault.svc:8200
    
          authentication: KUBERNETES
          kubernetes:
            role: order-app
            kubernetes-path: kubernetes
    
          database:
            enabled: true
            role: order-app
            backend: database
