apiVersion: v1
kind: Secret
metadata:
  name: person-app-db-secret
  labels:
    app: person-app-db
data:
  POSTGRES_PASSWORD: YWRtaW4xMjM=
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: person-app-db-pv-new
  labels:
    type: local
    app: person-app-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: person-app-db-claim
  labels:
    app: person-app-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-app-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-app-db
  template:
    metadata:
      labels:
        app: person-app-db
    spec:
      containers:
        - name: person-app-db
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: person-app-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: person-app-db-claim
---
apiVersion: v1
kind: Service
metadata:
  name: person-app-db
  labels:
    app: person-app-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: person-app-db

