---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  namespace: default
labels:
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: person-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-app-deployment
spec:
  selector:
    matchLabels:
      app: person-app
  template:
    metadata:
      labels:
        app: person-app
      annotations:
    spec:
      serviceAccountName: person-app-sa
      containers:
        - name: person-app
          image: dfrey501/person-app:0.0.1-SNAPSHOT
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"