debug: false

logging.level:
  org.springframework.data: DEBUG
  org.springframework.web: DEBUG
  com.vmware.tanzulabs.app: DEBUG

server:
  port: 8081

spring:

  application:
    name: order-app

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    log-request-details: true

  zipkin:
    enabled: false

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

#---
#spring:
#
#  config:
#    activate:
#      on-cloud-platform: kubernetes
#
#  cloud:
#
#    kubernetes:
#
#      config:
#        name: order-app
#        namespace: dfrey-dev
#        sources:
#          - namespace: dfrey-dev-config
#            name: order-app-cm
#
#      discovery:
#        enabled: true
#        all-namespaces: true
#
#server:
#  port: 8080
#
#---
#spring:
#
#  config:
#    activate:
#      on-profile: postgres
#
#  datasource:
#    url: jdbc:postgresql://order-app-db:5432/postgres
#
#---
#spring:
#
#  config:
#    activate:
#      on-profile: docker
#
#  zipkin:
#    enabled: true
#    base-url: http://monitoring-tempo-1:9411
#
#server:
#  port: 8080
#
#---
#spring:
#
#  config:
#    activate:
#      on-profile: vault
#
#    import: vault://
#
#  cloud:
#
#    vault:
#      enabled: true
#      fail-fast: true
#
#      config:
#        lifecycle:
#          enabled: true
#          min-renewal: 10m
#          expiry-threshold: 10m
#
#      kv.enabled: false
#
#      uri: http://vault.vault.svc:8200
#
#      authentication: KUBERNETES
#      kubernetes:
#        role: order-app
#        kubernetes-path: kubernetes
#
#      database:
#        enabled: true
#        role: order-app
#        backend: database
#
