kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-app
data:
  application.yml: |-
    logging.level:
      org.springframework.data: DEBUG
      com.vmware.tanzulabs.app: DEBUG

    spring:
      datasource:
        url: jdbc:postgresql://postgres:5432/postgres