debug: false

logging:
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web: DEBUG
    com.vmware.tanzulabs.app: DEBUG

spring:

  application:
    name: person-app

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    log-request-details: true

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always
    restart:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

webservice:
  order-resource-url: http://localhost:9081

---
spring:

  config:
    activate:
      on-profile: docker

logging:
  file:
    name: ${spring.application.name}.log


---
spring:

  config:
    activate:
      on-profile: kubernetes

logging.level:
  org.springframework.cloud.contract.stubrunner: INFO
  org.springframework.cloud.kubernetes: INFO
  org.springframework.data: INFO
  org.springframework.web: INFO
  com.vmware.tanzulabs.app: DEBUG

webservice:
  order-resource-url: http://order-app
