debug: false

logging.level:
  org.springframework.cloud.contract.stubrunner: DEBUG
  org.springframework.cloud.kubernetes: DEBUG
  org.springframework.data: DEBUG
  org.springframework.web: DEBUG
  com.vmware.tanzulabs.app: DEBUG

spring:

  application:
    name: person-app

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    log-request-details: true

  zipkin:
    enabled: false

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    restart:
      enabled: true

webservice:
  order-resource-url: http://localhost:8081

#---
#spring:
#
#  config:
#    activate:
#      on-profile: docker
#
#  zipkin:
#    enabled: true
#    base-url: http://tempo:9411
#
#webservice:
#  order-resource-url: http://order-app:8080
#
#---
#spring:
#
#  config:
#    activate:
#      on-profile: vault
#
#    import: vault://
#
#  cloud:
#
#    vault:
#      enabled: true
#      fail-fast: true
#
#      config:
#        lifecycle:
#          enabled: true
#          min-renewal: 10m
#          expiry-threshold: 10m
#
#      kv.enabled: false
#
#      uri: http://vault.vault.svc:8200
#
#      authentication: KUBERNETES
#      kubernetes:
#        role: person-app
#        kubernetes-path: kubernetes
#
#      database:
#        enabled: true
#        role: person-app
#        backend: database

