name: person-app-workflow

on:
  push:
    branches:
      - release/*
      - develop
      - feature/*
    paths:
      - 'app-parent/pom.xml'
      - 'app-parent/person-app/**'

jobs:

  checkout-source-job:
    name: Checkout Source flow
    uses: legos/legos-pipeline/.github/workflows/_checkout-source-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base:0.0.1

  checkout-settings-job:
    name: Checkout Settings flow
    uses: legos/legos-pipeline/.github/workflows/_checkout-settings-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base:0.0.1

  scan-source-owasp-job:
    name: Scan Source flow
    needs: [ checkout-source-job, checkout-settings-job ]
    uses: legos/legos-pipeline/.github/workflows/_scan-source-owasp-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/tc/ubuntu:22.04-openjdk17-build
      submodule: "person-app"
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

  scan-source-gitleaks-job:
    name: Scan Source flow
    needs: [ checkout-source-job ]
    uses: legos/legos-pipeline/.github/workflows/_scan-source-gitleaks-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/tc/ubuntu:22.04-openjdk17-build

  build-test-job:
    name: Build, Test flow
    needs: [ scan-source-owasp-job, scan-source-gitleaks-job ]
    uses: legos/legos-pipeline/.github/workflows/_build-test-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/tc/ubuntu:22.04-openjdk17-build
      submodule: "person-app"
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

#  scan-results-job:
#    name: Upload Scan Results
#    needs: [ build-test-job, scan-source-job ]
#    uses: legos/legos-pipeline/.github/workflows/_scan-results-action.yml@main
#    secrets:
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      NEXUS_USERNAME: ${{ secrets.AD_USER }}
#      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

  publish-artifact-job:
    name: Publish Artifact
    needs: [ build-test-job ]
    uses: legos/legos-pipeline/.github/workflows/_publish-artifact-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/tc/ubuntu:22.04-openjdk17-build
      submodule: "person-app"
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

  publish-image-job:
    name: Publish Image
    needs: [ publish-artifact-job ]
    uses: legos/legos-pipeline/.github/workflows/_publish-image-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/tc/ubuntu:22.04-openjdk17-build
      submodule: "person-app"
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USER }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASS }}
