name: person-app-workflow
# This is a caller workflow that calls a reusable workflow for non-containized projects.
on:
  push:
    branches:
      - release/*
      - develop
      - feature/*
    paths:
      - 'app-parent/person-app/**'

jobs:

  build-test-package:
    name: Build & Test Source

    runs-on: enterprise

    container:
      image: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base-jdk17:0.0.1

    env:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    steps:

      - name: Download Maven Settings
        uses: actions/download-artifact@v2
        with:
          name: maven-settings
          path: maven-settings

      - name: Download source
        uses: actions/download-artifact@v2
        with:
          name: source
          path: source

      - name: Setup Maven Repository Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-

      - name: Build, Test, Package source
        if: |
          contains(github.ref, 'develop') ||
          contains(github.ref, 'release')
        run: |
          cd source
          mvn -B -s ../maven-settings/settings.xml -P lego-nexus --no-transfer-progress -pl :person-app verify package
          cd ..

      - name: Build, Test, Verify source
        if: contains(github.ref, 'feature')
        run: |
          cd source
          mvn -B -s ../maven-settings/settings.xml -P lego-nexus --no-transfer-progress -pl :person-app verify
          cd ..

      - name: Upload source to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: source
