name: order-app-workflow

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/person-app-workflow.yml'
      - 'pom.xml'
      - 'app-parent/pom.xml'
      - 'app-parent/person-app/**'

jobs:

  build-and-test:
    name: Build and Test source
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: |
          ./mvnw -pl :person-app clean install
