name: person-app-workflow

on:
  push:
    branches:
      - release/*
      - develop
      - feature/*
    paths:
      - 'app-parent/person-app/**'

jobs:

  checkout-source-job:
    name: Checkout Source flow
    uses: legos/legos-pipeline/.github/workflows/_checkout-source-action.yml@main

  checkout-settings-job:
    name: Checkout Settings flow
    uses: legos/legos-pipeline/.github/workflows/_checkout-settings-action.yml@main

  build-test-job:
    name: Build, Test flow
    needs: [ checkout-source-job, checkout-settings-job ]
    uses: legos/legos-pipeline/.github/workflows/_build-test-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base-jdk17:0.0.1
      submodule: "person-app"
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

#  scan-source-job:
#    name: Scan Source flow
#    needs: [ checkout-source-job ]
#    uses: legos/legos-pipeline/.github/workflows/_scan-source-action.yml@main
#
#  scan-results-job:
#    name: Upload Scan Results
#    needs: [ build-test-job, scan-source-job ]
#    uses: legos/legos-pipeline/.github/workflows/_scan-results-action.yml@main
#    secrets:
#      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      NEXUS_USERNAME: ${{ secrets.AD_USER }}
#      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}

  publish-artifact-job:
    name: Publish Artifact
    needs: [ build-test-job ]
    uses: legos/legos-pipeline/.github/workflows/_publish-artifact-action.yml@main
    with:
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base-jdk17:0.0.1
    secrets:
      NEXUS_USERNAME: ${{ secrets.AD_USER }}
      NEXUS_PASSWORD: ${{ secrets.AD_PASS }}
