name: person-app-workflow

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/person-app-workflow.yml'
      - 'pom.xml'
      - 'app-parent/pom.xml'
      - 'app-parent/person-app/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: person-app
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build-and-test:
    name: Build and Test source

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get app version
        run: |
          echo "app_version=$(./mvnw -s settings.xml -pl :person-app help:evaluate -Dexpression=project.version -q -DforceStdout)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build, test and create the image
        run: |
          ./mvnw -B -s settings.xml \
          -pl :person-app \
          --no-transfer-progress \
          clean install deploy spring-boot:build-image \
          -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.app_version }} \
          -Dspring-boot.build-image.publish=true \
          -Ddocker.publishRegistry.username=${{ github.actor }} \
          -Ddocker.publishRegistry.password=${{ secrets.GITHUB_TOKEN }}
