name: person-app-workflow
# This is a caller workflow that calls a reusable workflow for non-containized projects.
on:
  push:
    branches:
      - 'master' 
    paths:
      - 'app-parent/person-app'

jobs:
  call-sast-workflow:
    uses: shredder/ds9-templates/.github/workflows/maven-sast-and-publish-called-reusable-workflow.yml@atlas-modified
    with:
      repositoryOwner: ${{ github.repository_owner }}
      repositoryName: ${{ github.event.repository.name }}
      sonarSources: app-parent/person-app/src/main/
      sonarTestPath: app-parent/person-app/src/test/
      sonarJavaLibrariesPath: target/
      branch: master      
      owaspSources:  artifacts/source
      buildImageUrl: harbor.cp.az.km.spaceforce.mil/ds9/ubuntu-base-jdk11:0.0.1
      commitSha:  ${{ github.sha }}
    secrets:
      token: ${{ secrets.GHA_CLONE_REPOS_PAT }}
      nexus_username: ${{ secrets.AD_USER }} 
      nexus_password:  ${{ secrets.AD_PASS }}
      owasp_dc_db_pass: ${{ secrets.OWASP_DC_DB_PASS}} 
      gh_issues_db_addr: ${{secrets.GH_ISSUES_DB_ADDR}}
      gh_issues_user: ${{secrets.GH_ISSUES_USER}}
      gh_issues_pass: ${{secrets.GH_ISSUES_PASS}}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
