apiVersion: v1
kind: Secret
metadata:
  name: demo-parent-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.km.spaceforce.mil/legos-test/demo-parent
  password: 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
  username: daniel.frey.ctr@kmdevspace.onmicrosoft.us